function trackers = config_tracker()
% config trackers to be evaluated
% struct('name', 'DUTrack250actor26notagtoinitlan',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250actor26',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250notagtoinitlan2',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250notagtoinitlan',       'publish', 'ahaha2') ...

% struct('name', 'actor170_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor150_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval500',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval300',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval500',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval300',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval100',       'publish', 'ahaha2') ...
trackers = {
            struct('name', 'actor20_interval100_removeiou',       'publish', 'ahaha2') ...
            struct('name', 'actor20_interval100_removejude',       'publish', 'ahaha2') ...
            struct('name', 'actor20_interval100',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval50',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval300',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval500',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval1000',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval300_sta_update',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval300_sta_dya_update',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval300_dya_sta_update',       'publish', 'ahaha2') ...
            struct('name', 'actor90_interval300_ddupdate',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack_baselineTracker2',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack_notupdate',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack_nolan',       'publish', 'ahaha2') ...
            struct('name', 'actor170_interval100',       'publish', 'ahaha2') ...
            struct('name', 'actor150_interval100',       'publish', 'ahaha2') ...
            struct('name', 'actor130_interval500',       'publish', 'ahaha2') ...
            struct('name', 'actor130_interval300',       'publish', 'ahaha2') ...
            struct('name', 'actor130_interval100',       'publish', 'ahaha2') ...
            struct('name', 'actor110_interval500',       'publish', 'ahaha2') ...
            struct('name', 'actor110_interval300',       'publish', 'ahaha2') ...
            struct('name', 'actor110_interval100',       'publish', 'ahaha2') ...
            struct('name', 'DUTrackfull90step',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack250of250rl30stepStatic',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack250of250rl30step',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack_sft',       'publish', 'ahaha2') ...
            struct('name', 'DUTrack_baselineTracker2',       'publish', 'ahaha2') ...
            };

end