function trackers = config_tracker()
% config trackers to be evaluated
% struct('name', 'DUTrack250actor26notagtoinitlan',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250actor26',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250notagtoinitlan2',       'publish', 'ahaha2') ...
% struct('name', 'DUTrack250notagtoinitlan',       'publish', 'ahaha2') ...

% struct('name', 'actor170_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor150_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval500',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval300',       'publish', 'ahaha2') ...
% struct('name', 'actor130_interval100',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval500',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval300',       'publish', 'ahaha2') ...
% struct('name', 'actor110_interval100',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack250of250rl30stepStatic',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack250of250rl30step',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack100of250rl25step',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack_sft',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack_baselineTracker2',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack_notupdate',       'publish', 'ahaha2') ...
%             struct('name', 'DUTrack_nolan',       'publish', 'ahaha2') ...
%             struct('name', 'dutrack1100',       'publish', 'ahaha') ...
trackers = {
%             DUTrackfull90step、DUTrack_baselineTracker2
            struct('name', 'lantrack_256_base_045',       'publish', 'ahaha2') ...
%             struct('name', 'lantrack_256_cac_mvp_N_2_landa_0.5_45',       'publish', 'ahaha2') ...
%             struct('name', 'dutrack',       'publish', 'ahaha2') ...
%             struct('name', 'ReasoningTrack',       'publish', 'ahaha2') ...
%             struct('name', 'uvltrackNLBB',       'publish', 'ahaha2') ...
%             struct('name', 'uvltrackNL',       'publish', 'ahaha2') ...
%             struct('name', 'uvltrackBB',       'publish', 'ahaha2') ...
%             struct('name', 'sutrack',       'publish', 'ahaha2') ...
%             struct('name', 'romtrack',       'publish', 'ahaha2') ...
%             struct('name', 'ostrack',       'publish', 'ahaha2') ...
%             struct('name', 'odtrack',       'publish', 'ahaha2') ...
%             struct('name', 'mmtrack',       'publish', 'ahaha2') ...
%             struct('name', 'mixformer',       'publish', 'ahaha2') ...
%             struct('name', 'lmtrack',       'publish', 'ahaha2') ...
%             struct('name', 'jointNLTrack',       'publish', 'ahaha2') ...
%             struct('name', 'jointNL',       'publish', 'ahaha2') ...
%             struct('name', 'evptrack',       'publish', 'ahaha2') ...
%             struct('name', 'ctvlt',       'publish', 'ahaha2') ...
%             struct('name', 'citetrack',       'publish', 'ahaha2') ...
%             struct('name', 'aqatrack',       'publish', 'ahaha2') ...
%             struct('name', 'allinone',       'publish', 'ahaha2') ...
%             struct('name', 'aiatrack',       'publish', 'ahaha2') ...
%             struct('name', 'grm',       'publish', 'ahaha2') ...

            };

end